const okrObjectives = [
  {
    id: 'refahjib', team: 'رفاه‌جیب', owner: 'کاریز',
    title: 'اثبات رفاه‌جیب به‌عنوان راهکار اعتباری قابل توسعه برای سازمان‌ها و کارکنان',
    krs: [
      {title:'رسیدن به 50 شرکت فعال',owner:'کاریز',unit:'رفاه‌جیب',kpi:'Active Organizations',target:50,actual:3,weight:25,progress:6,status:'off',blocker:'با ۴ شرکت نهایی شده، قرارداد و مدارک تبادل شده اما به دلیل نداشتن شبکه دیبا و خط اعتباری بلاک شده است'},
      {title:'فعال‌سازی 10,000 کاربر نهایی',owner:'کاریز',unit:'رفاه‌جیب',kpi:'Activated Users',target:10000,actual:300,weight:25,progress:3,status:'off'},
      {title:'تخصیص 400 میلیارد تومان تسهیلات',owner:'کاریز',unit:'رفاه‌جیب',kpi:'Credit Volume',target:400,actual:0,weight:30,progress:0,status:'off'},
      {title:'عملیاتی‌شدن کامل فرایند شرکت تا بازپرداخت',owner:'کاریز',unit:'رفاه‌جیب / محصول',kpi:'E2E Readiness',target:1,actual:0,weight:20,progress:0,status:'off'}
    ]
  },
  {
    id: 'bizjib', team: 'بیزجیب', owner: 'عبدی',
    title: 'اثبات مدل بیزجیب و ایجاد پرتفوی اولیه مشتریان تجاری',
    krs: [
      {title:'رسیدن به 20 شرکت فعال',owner:'عبدی',unit:'بیزجیب',kpi:'Active Companies',target:20,actual:1,weight:25,progress:5,status:'off'},
      {title:'فعال‌سازی 2,000 کاربر نهایی',owner:'عبدی',unit:'بیزجیب',kpi:'Activated Users',target:2000,actual:0,weight:20,progress:0,status:'off'},
      {title:'تخصیص 270 میلیارد تومان تسهیلات',owner:'عبدی',unit:'بیزجیب',kpi:'Credit Volume',target:370,actual:0,weight:35,progress:0,status:'review',blocker:'در انتظار تأمین',note:'عدد Target در فایل ۳۷۰ است و با عدد ۲۷۰ در عنوان KR نیاز به تطبیق دارد.'},
      {title:'عملیاتی‌شدن کامل فرایند شرکت تا بازپرداخت',owner:'عبدی',unit:'بیزجیب / محصول',kpi:'E2E Readiness',target:1,actual:0,weight:20,progress:0,status:'off'}
    ]
  },
  {
    id: 'jibplus', team: 'جیب‌پلاس', owner: 'فیض',
    title: 'اثبات و تثبیت جیب‌پلاس به‌عنوان یکی از لاین‌های اصلی کسب‌وکار همراه‌جیب',
    krs: [
      {title:'تعیین و تصویب تارگت‌های تجاری جیب‌پلاس برای فصل',owner:'فیض',kpi:'Targets Approved',target:null,actual:null,weight:25,progress:null,status:'pending'},
      {title:'تحقق هدف فعال‌سازی کاربران جیب‌پلاس',owner:'فیض',kpi:'Activated Users',target:null,actual:null,weight:25,progress:null,status:'pending'},
      {title:'تحقق هدف حجم عملیات و درآمد جیب‌پلاس',owner:'فیض',kpi:'Volume / Revenue',target:null,actual:null,weight:25,progress:null,status:'pending'},
      {title:'آمادگی کامل فرایند End-to-End جیب‌پلاس',owner:'فیض',kpi:'E2E Readiness',target:null,actual:null,weight:25,progress:null,status:'pending'}
    ]
  },
  {
    id: 'funding', team: 'تأمین منابع', owner: 'فیض',
    title: 'تأمین پایدار منابع موردنیاز رشد',
    krs: [
      {title:'ایجاد 770 میلیارد توان ظرفیت خط اعتباری قابل استفاده',owner:'فیض',kpi:'Available Credit Line',target:770,actual:0,weight:40,progress:0,status:'off'},
      {title:'تثبیت خط اعتباری در مصوبه مربوطه',owner:'فیض',kpi:'Approval',target:1,actual:0,weight:20,progress:0,status:'off'},
      {title:'طراحی فرایند استاندارد درخواست، تخصیص و مصرف منابع',owner:'فیض',kpi:'Process Readiness',target:1,actual:0,weight:15,progress:0,status:'off'},
      {title:'استقرار گزارش مانده، مصرف و ظرفیت‌های خطوط اعتباری',owner:'فیض',kpi:'Funding Dashboard',target:1,actual:0,weight:15,progress:0,status:'off'},
      {title:'تعریف و تصویب چارچوب تصمیم‌گیری تأمین مالی',owner:'فیض',kpi:'Governance',target:1,actual:0,weight:10,progress:0,status:'off'}
    ]
  },
  {
    id: 'product', team: 'محصول و فناوری', owner: 'کیارش',
    title: 'تبدیل رفاه‌جیب، بیزجیب و جیب‌پلاس به محصولات End-to-End قابل بهره‌برداری',
    krs: [
      {title:'Go-Live رفاه‌جیب',owner:'کیارش',kpi:'Readiness',target:1,actual:0.15,weight:20,progress:15,status:'off',blocker:'سرویس TMS و اعتبار بانک ملی یا دی'},
      {title:'Go-Live بیزجیب',owner:'کیارش',kpi:'Readiness',target:1,actual:0.17,weight:20,progress:17,status:'off',blocker:'سرویس TMS و اعتبار بانک ملی یا دی'},
      {title:'تکمیل ثبت شرکت و کاربر',owner:'کیارش',kpi:'E2E Process',target:1,actual:0.15,weight:15,progress:15,status:'off',blocker:'سرویس TMS و اعتبار بانک ملی یا دی'},
      {title:'تکمیل فرایند تخصیص اعتبار',owner:'کیارش',kpi:'E2E Process',target:1,actual:0.3,weight:15,progress:30,status:'off',blocker:'سرویس TMS و اعتبار بانک ملی یا دی'},
      {title:'تکمیل فرایند مدیریت بازپرداخت',owner:'کیارش',kpi:'E2E Process',target:1,actual:0.2,weight:15,progress:20,status:'off',blocker:'سرویس TMS و اعتبار بانک ملی یا دی'},
      {title:'راه‌اندازی پنل عملیاتی و گزارش‌های پایه',owner:'کیارش',kpi:'Backoffice Readiness',target:1,actual:0,weight:15,progress:0,status:'off'}
    ]
  },
  {
    id: 'security', team: 'محصول و فناوری', owner: 'افشار',
    title: 'ایجاد حداقل استاندارد امنیت قابل اتکا برای Go-Live و رشد',
    krs: [
      {title:'تکمیل ارزیابی امنیتی سرویس‌ها و ثبت ریسک‌های بحرانی',owner:'تیم خارجی ـ قرارداد در حال امضا',kpi:'Security Assessment',target:1,actual:0,weight:25,progress:0,status:'off'},
      {title:'فعال‌سازی MFA و کنترل دسترسی مبتنی بر حداقل سطح دسترسی برای محیط‌های حساس',owner:'تیم خارجی ـ قرارداد در حال امضا',kpi:'Access Control Coverage',target:1,actual:0,weight:25,progress:0,status:'off'},
      {title:'بستن تمام آسیب‌پذیری‌های Critical پیش از Go-Live',owner:'تیم خارجی ـ قرارداد در حال امضا',kpi:'Critical Vulnerabilities Closed',target:1,actual:0,weight:25,progress:0,status:'off'},
      {title:'استقرار لاگ امنیتی',owner:'تیم خارجی ـ قرارداد در حال امضا',kpi:'Security Monitoring Readiness',target:1,actual:0,weight:25,progress:0,status:'off'}
    ]
  },
  {
    id: 'operations', team: 'عملیات', owner: 'ساسان',
    title: 'ایجاد عملیات قابل کنترل برای پشتیبانی از اولین ۱۲ هزار کاربر',
    krs: [
      {title:'راه‌اندازی فرآیند عملیاتی شرکت و کاربر',owner:'ساسان',kpi:'Process Readiness',target:1,actual:0,weight:20,progress:0,status:'off',blocker:'Go-Live فرایند عملیاتی شرکت‌ها'},
      {title:'راه‌اندازی فرآیند تخصیص و کنترل اعتبار',owner:'ساسان',kpi:'Process Readiness',target:1,actual:0.2,weight:20,progress:20,status:'off',blocker:'انجام فرآیند تخصیص اعتبار اولیه برای کاربران داخلی، سنجش تجربه و شناسایی گلوگاه‌ها برای بهبود فاز دوم'},
      {title:'راه‌اندازی فرآیند بازپرداخت',owner:'ساسان',kpi:'Repayment Ops',target:1,actual:0.1,weight:20,progress:10,status:'off',blocker:'نیاز به دسترسی پنل کلی، ارائه اولیه فرایند بازپرداخت و دسترسی کارشناسان عملیات'},
      {title:'راه‌اندازی کال‌سنتر اولیه',owner:'ساسان',kpi:'Call Center Readiness',target:1,actual:0.6,weight:15,progress:60,status:'risk',blocker:'جذب نفر چهارم، فضای کاری، ابزار سخت‌افزاری و CRM'},
      {title:'تعریف فرآیند Escalation مشکلات',owner:'ساسان',kpi:'Escalation Process',target:1,actual:0.2,weight:10,progress:20,status:'off',blocker:'نیاز به CRM، SLA و Owner نهایی بین تیم‌های داخلی سازمان'},
      {title:'گزارش عملیاتی دوره‌ای',owner:'ساسان',kpi:'Ops Reporting',target:1,actual:0.6,weight:15,progress:60,status:'risk',blocker:'زمان‌بندی، مالکیت، مخاطب و فرمت نهایی گزارش‌ها هنوز به‌صورت رسمی تثبیت نشده است'}
    ]
  },
  {
    id: 'finance', team: 'مالی و ریسک', owner: 'ابداری',
    title: 'ایجاد کنترل مالی و اعتباری لازم برای رشد سالم پرتفوی',
    krs: [
      {title:'گزارش درآمد و هزینه هر Business Line',owner:'ابداری',kpi:'Monthly P&L',target:1,actual:0.2,weight:20,progress:20,status:'off'},
      {title:'گزارش مصرف خطوط اعتباری',owner:'ابداری',kpi:'Credit Utilization Report',target:1,actual:0,weight:20,progress:0,status:'off'},
      {title:'تعریف چارچوب کنترل ریسک اعتباری',owner:'ابداری',kpi:'Risk Framework',target:1,actual:0,weight:20,progress:0,status:'off'},
      {title:'ایجاد گزارش بازپرداخت و مطالبات',owner:'ابداری',kpi:'Repayment & Receivables',target:1,actual:0,weight:20,progress:0,status:'off'},
      {title:'استقرار گزارش مدیریتی مالی فصل',owner:'ابداری',kpi:'Finance Management Report',target:1,actual:0.2,weight:20,progress:20,status:'off'}
    ]
  },
  {
    id: 'marketing', team: 'بازاریابی', owner: 'عسگریان',
    title: 'پشتیبانی از رشد رفاه‌جیب، بیزجیب و جیب‌پلاس و فعال‌سازی کاربران جذب‌شده',
    krs: [
      {title:'پشتیبانی از فعال‌سازی کاربران رفاه‌جیب',owner:'عسگریان',kpi:'Activated Users',target:10000,actual:0,weight:30,progress:0,status:'off'},
      {title:'پشتیبانی از فعال‌سازی کاربران بیزجیب',owner:'عسگریان',kpi:'Activated Users',target:2000,actual:0,weight:20,progress:0,status:'off'},
      {title:'تعیین Target مارکتینگ جیب‌پلاس پس از تصویب هدف تجاری لاین',owner:'عسگریان',kpi:'JibPlus Marketing Target',target:null,actual:null,weight:15,progress:null,status:'pending'},
      {title:'آماده‌سازی Sales Kit برای سه لاین کسب‌وکار',owner:'عسگریان',kpi:'Sales Enablement',target:1,actual:0,weight:15,progress:0,status:'off'},
      {title:'طراحی فرآیند ارتباط با کاربران سازمان‌های جدید و استقرار گزارش عملکرد مارکتینگ',owner:'عسگریان',kpi:'Lifecycle & Reporting',target:1,actual:0,weight:20,progress:0,status:'off'}
    ]
  },
  {
    id: 'hr', team: 'منابع انسانی', owner: 'یاسین',
    title: 'ساخت تیم موردنیاز برای اجرای فاز اول و آماده‌سازی سازمان برای مرحله تثبیت',
    krs: [
      {title:'تأمین ساختار نیروی انسانی فاز اول طبق Plan',owner:'یاسین',kpi:'Workforce Readiness',target:1,actual:0,weight:30,progress:0,status:'off'},
      {title:'تعیین Owner تمام KRهای شرکت',owner:'یاسین',kpi:'OKR Ownership',target:1,actual:0,weight:20,progress:0,status:'off'},
      {title:'تعریف Job Description نقش‌های کلیدی',owner:'یاسین',kpi:'JD Completion',target:1,actual:0,weight:15,progress:0,status:'off'},
      {title:'استقرار ارزیابی عملکرد مبتنی بر OKR',owner:'یاسین',kpi:'Performance System',target:1,actual:0,weight:20,progress:0,status:'off'},
      {title:'آماده‌سازی Workforce Plan فصل بعد',owner:'یاسین',kpi:'Workforce Plan',target:1,actual:0,weight:15,progress:0,status:'off'}
    ]
  },
  {
    id: 'support', team: 'پشتیبانی سازمانی', owner: 'نیازمند تصویب',
    title: 'فراهم‌کردن به‌موقع فضای کار، تجهیزات، خدمات پشتیبان و مشاوران موردنیاز برای اجرای بدون وقفه اهداف فصل اول',
    krs: [
      {title:'آماده‌سازی کامل فضای کاری فاز اول برای حداقل ۴۵ نفر',owner:'نیازمند تصویب',kpi:'Workspace Readiness',target:1,actual:0,weight:20,progress:0,status:'pending'},
      {title:'تأمین و تحویل تجهیزات کاری تمام نیروهای فعال پیش از شروع به کار',owner:'نیازمند تصویب',kpi:'Equipment Delivery',target:1,actual:0,weight:20,progress:0,status:'pending'},
      {title:'استقرار زیرساخت‌های عمومی و ارتباطی',owner:'نیازمند تصویب',kpi:'Infrastructure Readiness',target:1,actual:0,weight:15,progress:0,status:'pending'},
      {title:'تأمین نرم‌افزارها، مجوزها و خدمات عمومی مصوب پیش از نیاز عملیاتی',owner:'نیازمند تصویب',kpi:'Services Readiness',target:1,actual:0,weight:15,progress:0,status:'pending'},
      {title:'عقد و فعال‌سازی قرارداد مشاوران و تأمین‌کنندگان حیاتی مصوب فصل',owner:'نیازمند تصویب',kpi:'Critical Contracts',target:1,actual:0,weight:15,progress:0,status:'pending'},
      {title:'استقرار نظام درخواست خرید، تحویل، ثبت، تخصیص، نگهداری و بازپس‌گیری دارایی‌ها',owner:'نیازمند تصویب',kpi:'Asset Management',target:1,actual:0,weight:10,progress:0,status:'pending'},
      {title:'استقرار گزارش ماهانه بودجه و هزینه منابع، تجهیزات، مشاوران و خدمات پشتیبان',owner:'نیازمند تصویب',kpi:'Support Cost Report',target:1,actual:0,weight:5,progress:0,status:'pending'}
    ]
  }
];

const masterPrerequisiteRecords = [
  {
    id: "md-pre-1-1",
    title: "منابع موجود در برنامه",
    requestTeam: "رفاه‌جیب",
    objectiveId: "refahjib",
    requester: "کاریز",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "۴۰۰ میلیارد تومان ظرفیت اعتباری؛ یک مدیر لاین، سه کارشناس فروش فنی و پنج نیروی کال‌سنتر تا ماه سوم؛ ۳.۵ میلیارد تومان بودجه جذب شرکت؛ ۱.۵ میلیارد تومان هزینه عملیات کارت؛ سهم از بودجه بازاریابی عمومی و نگهداشت.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-1-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "رفاه‌جیب",
    objectiveId: "refahjib",
    requester: "کاریز",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "سهم دقیق رفاه‌جیب از بودجه عمومی بازاریابی و نگهداشت، ظرفیت پشتیبانی مالی و اعتباری، و کف ظرفیت عملیاتی لازم برای ۵۰ شرکت و ۱۰٬۰۰۰ کاربر.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-1-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "رفاه‌جیب",
    objectiveId: "refahjib",
    requester: "کاریز",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "مشاور حقوقی قراردادهای سازمانی، مشاور ریسک اعتباری و مشاور عملیات بانکی/کارت؛ همراه با دامنه خدمت، بودجه و زمان شروع.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-1-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "رفاه‌جیب",
    objectiveId: "refahjib",
    requester: "کاریز",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "۹ جایگاه اختصاصی لاین در ماه سوم، پنج جایگاه مجهز کال‌سنتر، فضای مذاکره با سازمان‌ها، رایانه، تلفن، هدست و دسترسی‌های عملیاتی؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-2-1",
    title: "منابع موجود در برنامه",
    requestTeam: "بیزجیب",
    objectiveId: "bizjib",
    requester: "عبدی",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "۳۷۰ میلیارد تومان ظرفیت اعتباری؛ یک مدیر لاین، ۰.۸ کارشناس فروش فنی و یک نیروی کال‌سنتر تا ماه سوم؛ ۱.۴ میلیارد تومان بودجه جذب شرکت و ۳۰۰ میلیون تومان هزینه عملیات کارت.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-2-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "بیزجیب",
    objectiveId: "bizjib",
    requester: "عبدی",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "کف ظرفیت فروش، تحلیل اعتباری و عملیات لازم برای ۲۰ شرکت و ۳۷۰ میلیارد تومان اعتبار؛ همچنین تصمیم درباره افزایش ظرفیت ۰.۸ نفر فروش فنی به حداقل یک نیروی کامل.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-2-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "بیزجیب",
    objectiveId: "bizjib",
    requester: "عبدی",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "مشاور اعتبارات کسب‌وکار، مشاور حقوقی قرارداد و تضامین و در صورت استفاده از مدل زنجیره‌ای، مشاور تأمین مالی زنجیره‌ای.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-2-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "بیزجیب",
    objectiveId: "bizjib",
    requester: "عبدی",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "حداقل سه جایگاه اختصاصی لاین، فضای جلسه و بررسی اسناد مشتریان، تجهیزات تماس و دسترسی امن به اسناد و سامانه‌های اعتبار؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-3-1",
    title: "منابع موجود در برنامه",
    requestTeam: "جیب‌پلاس",
    objectiveId: "jibplus",
    requester: "فیض",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "۹ میلیارد تومان بودجه عمومی B2C و ۲.۷ میلیارد تومان بودجه نگهداشت در سطح شرکت؛ فرضیه‌های اولیه کاربر، تراکنش و درآمد در مدل مالی که تا زمان تصویب، Target رسمی OKR نیستند.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-3-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "جیب‌پلاس",
    objectiveId: "jibplus",
    requester: "فیض",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "Owner فردی، ساختار تیم اختصاصی، Targetهای تجاری، سهم بودجه بازاریابی، بودجه مشوق فعال‌سازی، هزینه عملیات و نقدینگی موردنیاز لاین.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-3-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "جیب‌پلاس",
    objectiveId: "jibplus",
    requester: "فیض",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "پس از تعیین دامنه نهایی محصول، مشاور حقوقی و تطبیق مقررات، مشاور مدل درآمدی/نقدینگی و متخصص حوزه محصول مربوطه.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-3-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "جیب‌پلاس",
    objectiveId: "jibplus",
    requester: "فیض",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "جایگاه تیم لاین در فضای مشترک محصول و کسب‌وکار، تجهیزات تست کاربر و دسترسی به زیرساخت‌های عملیاتی؛ تعداد دقیق پس از تصویب ساختار تیم از مسیر O11 تأمین شود.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-4-1",
    title: "منابع موجود در برنامه",
    requestTeam: "تأمین منابع",
    objectiveId: "funding",
    requester: "فیض",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "۷۷۰ میلیارد تومان ظرفیت خط اعتباری و حدود ۲۶.۹۵ میلیارد تومان هزینه پول سه‌ماهه؛ مشارکت مدیریت ارشد، سهامداران و تیم حسابداری.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-4-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "تأمین منابع",
    objectiveId: "funding",
    requester: "فیض",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "یک Owner اجرایی فردی برای تأمین مالی، ظرفیت تخصصی خزانه‌داری و ارتباط با بانک، سقف هزینه پول، برنامه نقدینگی و منابع لازم برای پوشش کسری عملیاتی فصل.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-4-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "تأمین منابع",
    objectiveId: "funding",
    requester: "فیض",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "مشاور ساختاردهی مالی، وکیل متخصص قراردادهای بانکی و در صورت نیاز مشاور مستقل مذاکره و تأمین خط اعتباری.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-4-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "تأمین منابع",
    objectiveId: "funding",
    requester: "فیض",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "فضای مذاکره و جلسه با بانک‌ها، محل امن نگهداری قراردادها و اسناد، تجهیزات ارتباطی و دسترسی محدود به اطلاعات مالی؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-5-1",
    title: "منابع موجود در برنامه تا ماه سوم",
    requestTeam: "محصول و فناوری",
    objectiveId: "product",
    requester: "کیارش",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "یک مدیر ارشد محصول/فنی/عملیات، دو مدیر محصول، چهار توسعه‌دهنده بک‌اند، یک توسعه‌دهنده فرانت‌اند، دو توسعه‌دهنده اپلیکیشن، یک طراح رابط کاربری، یک DevOps، یک اسکرام‌مستر و یک نیروی Help Center؛ حدود یک میلیارد تومان هزینه سرور و حدود ۶.۹۷ میلیارد تومان تجهیزات و سرمایه‌گذاری مستقیم فناوری.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-5-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "محصول و فناوری",
    objectiveId: "product",
    requester: "کیارش",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "ظرفیت QA و آزمون نرم‌افزار، تحلیل کسب‌وکار، داده و BI، یکپارچه‌سازی بانکی و مالک داخلی امنیت؛ تعیین اینکه این ظرفیت‌ها استخدام، تخصیص داخلی یا برون‌سپاری شوند.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-5-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "محصول و فناوری",
    objectiveId: "product",
    requester: "کیارش",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "مشاور معماری فنی و یکپارچه‌سازی بانکی و در صورت نبود تخصص داخلی، مشاور داده و قابلیت اطمینان سرویس.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-5-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "محصول و فناوری",
    objectiveId: "product",
    requester: "کیارش",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "فضای تیم فنی و محصول، رایانه مناسب توسعه، تجهیزات تست موبایل، شبکه پایدار، اینترنت پشتیبان، محیط‌های مجزای توسعه/آزمون/عملیاتی و زیرساخت سرور؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-6-1",
    title: "منابع موجود در برنامه",
    requestTeam: "محصول و فناوری",
    objectiveId: "security",
    requester: "افشار",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "تیم امنیت خارجی در حال قرارداد و ظرفیت مشترک DevOps.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-6-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "محصول و فناوری",
    objectiveId: "security",
    requester: "افشار",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "بودجه مستقل امنیت، تعیین مسئول امنیت داخلی، ظرفیت رفع آسیب‌پذیری در تیم فنی و بودجه ابزارهای کنترل دسترسی، مانیتورینگ و پشتیبان‌گیری.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-6-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "محصول و فناوری",
    objectiveId: "security",
    requester: "افشار",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "نهایی‌سازی قرارداد تیم ارزیابی امنیت و آزمون نفوذ و در صورت نیاز مشاور حریم خصوصی و تطبیق مقررات.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-6-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "محصول و فناوری",
    objectiveId: "security",
    requester: "افشار",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "دسترسی فیزیکی و سیستمی محدود، محیط امن آزمون، تجهیزات و حساب‌های مجزای ارزیابی، فضای امن نگهداری گزارش‌های امنیتی و زیرساخت پشتیبان؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-7-1",
    title: "منابع موجود در برنامه تا ماه سوم",
    requestTeam: "عملیات",
    objectiveId: "operations",
    requester: "ساسان",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "یک مدیر پشتیبانی، یک نیروی Help Center، پنج نیروی کال‌سنتر رفاه‌جیب، یک نیروی کال‌سنتر بیزجیب و سه نیروی لجستیک/عملیات عمومی؛ ۱۵ میلیون تومان هزینه VoIP و ۱.۸ میلیارد تومان هزینه عملیات کارت دو لاین.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-7-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "عملیات",
    objectiveId: "operations",
    requester: "ساسان",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "ظرفیت وصول مطالبات، مغایرت و تسویه، کنترل کیفیت عملیات، برنامه‌ریزی نیروی کال‌سنتر و عملیات تقلب؛ تعیین مدل استخدام یا برون‌سپاری هرکدام.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-7-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "عملیات",
    objectiveId: "operations",
    requester: "ساسان",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "مشاور راه‌اندازی کال‌سنتر و در صورت نیاز مشاور طراحی عملیات و کنترل کیفیت.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-7-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "عملیات",
    objectiveId: "operations",
    requester: "ساسان",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "فضای مجزای کال‌سنتر با حداقل شش جایگاه، فضای عملیات و بررسی اسناد، خطوط تلفن و VoIP، هدست، رایانه، اینترنت پشتیبان و تجهیزات ضبط و کنترل تماس؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-8-1",
    title: "منابع موجود در برنامه",
    requestTeam: "مالی و ریسک",
    objectiveId: "finance",
    requester: "ابداری",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "سه نیروی حسابداری در ماه سوم، ۳۰۰ میلیون تومان سرمایه‌گذاری برای نرم‌افزار مالی و دسترسی به داده‌های درآمد، هزینه، اعتبار و بازپرداخت.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-8-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "مالی و ریسک",
    objectiveId: "finance",
    requester: "ابداری",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "ظرفیت تخصصی ریسک اعتباری، FP&A، تحلیل پرتفوی، کنترل داخلی و وصول؛ تصویب Targetهای نکول، PAR، نرخ وصول و هزینه ریسک.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-8-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "مالی و ریسک",
    objectiveId: "finance",
    requester: "ابداری",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "مشاور ریسک اعتباری، حسابرس/مشاور مالیاتی و در صورت نیاز مشاور طراحی کنترل‌های داخلی و ذخیره‌گیری مطالبات.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-8-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "مالی و ریسک",
    objectiveId: "finance",
    requester: "ابداری",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "فضای کنترل‌شده مالی، محل امن اسناد و تضامین، رایانه و دسترسی محدود، نرم‌افزار مالی و تجهیزات تهیه و نگهداری نسخه پشتیبان؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-9-1",
    title: "منابع موجود در برنامه تا ماه سوم",
    requestTeam: "بازاریابی",
    objectiveId: "marketing",
    requester: "عسگریان",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "یک مدیر بازاریابی، یک مدیر محتوا، یک کارشناس محتوا و سئو، سه کارشناس شبکه اجتماعی و سه طراح گرافیک؛ ۹ میلیارد تومان بودجه عمومی B2C، ۲.۷ میلیارد تومان بودجه نگهداشت، ۴.۹ میلیارد تومان بودجه جذب شرکت‌های رفاه‌جیب و بیزجیب و ۵۰۰ میلیون تومان تجهیزات استودیو.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-9-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "بازاریابی",
    objectiveId: "marketing",
    requester: "عسگریان",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "ظرفیت بازاریابی B2B، بازاریابی محصول، CRM/Lifecycle و تحلیل داده رشد؛ تخصیص دقیق بودجه عمومی میان لاین‌ها و تعیین بودجه جیب پلاس.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-9-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "بازاریابی",
    objectiveId: "marketing",
    requester: "عسگریان",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "در صورت نبود ظرفیت داخلی، مشاور تحقیقات بازار، استراتژی رسانه، اجرای کمپین و سنجش اثربخشی.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-9-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "بازاریابی",
    objectiveId: "marketing",
    requester: "عسگریان",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "فضای تیم بازاریابی، استودیوی محتوا، تجهیزات تصویربرداری و تدوین، فضای جلسه کمپین و تجهیزات تست ارتباطات کاربر؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-10-1",
    title: "منابع موجود در برنامه",
    requestTeam: "منابع انسانی",
    objectiveId: "hr",
    requester: "یاسین",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "رشد ظرفیت سازمان از ۲۷.۷۵ نفر در ماه اول به ۴۳.۸ نفر در ماه سوم، حدود ۱۸.۰۳ میلیارد تومان حقوق طبق شیت HR و فضای کاری ۴۵نفره.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-10-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "منابع انسانی",
    objectiveId: "hr",
    requester: "یاسین",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "حداقل یک مسئول منابع انسانی و ظرفیت جذب/استخدام، بودجه جذب و آموزش، تعیین تکلیف ضریب دوبرابری هزینه حقوق در شیت Opex و اولویت‌بندی استخدام نقش‌های حیاتی.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-10-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "منابع انسانی",
    objectiveId: "hr",
    requester: "یاسین",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "مشاور قانون کار و جبران خدمات و در صورت نیاز مشاور طراحی سازمان، شایستگی و ارزیابی عملکرد.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-10-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "منابع انسانی",
    objectiveId: "hr",
    requester: "یاسین",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "۴۵ جایگاه کاری، برنامه تخصیص صندلی و تجهیزات به تفکیک واحد، اتاق جلسات، فضای مصاحبه و Onboarding و دسترسی‌های موردنیاز هر نقش؛ تأمین از مسیر O11.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-11-1",
    title: "منابع موجود در برنامه",
    requestTeam: "پشتیبانی سازمانی",
    objectiveId: "support",
    requester: "نیازمند تصویب",
    supplyOwner: "طبق برنامه مصوب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "حدود ۱.۰۴ میلیارد تومان هزینه آماده‌سازی فضای کار، یک میلیارد تومان هزینه سرور، ۱۵ میلیون تومان هزینه VoIP و حدود ۷.۹۴ میلیارد تومان Capex شامل تجهیزات فناوری، استودیو، نرم‌افزار مالی و هزینه‌های ثبتی.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-11-2",
    title: "منابع نیازمند تصویب",
    requestTeam: "پشتیبانی سازمانی",
    objectiveId: "support",
    requester: "نیازمند تصویب",
    supplyOwner: "نیازمند تصویب",
    category: "Resources",
    progress: 0,
    status: "requested",
    impact: "بودجه نهایی فضای کار و تجهیزات، فهرست استاندارد تجهیزات هر نقش، بودجه نرم‌افزارها و مجوزها، بودجه مشاوران و سطح ذخیره احتیاطی تعمیر و جایگزینی.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-11-3",
    title: "مشاوران نیازمند تصویب",
    requestTeam: "پشتیبانی سازمانی",
    objectiveId: "support",
    requester: "نیازمند تصویب",
    supplyOwner: "نیازمند تصویب",
    category: "Consulting",
    progress: 0,
    status: "requested",
    impact: "فهرست نهایی مشاوران مشترک شرکت، دامنه خدمت، خروجی قابل تحویل، Owner داخلی، مبلغ قرارداد و زمان شروع هر خدمت.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  },
  {
    id: "md-pre-11-4",
    title: "فضای کار و تجهیزات",
    requestTeam: "پشتیبانی سازمانی",
    objectiveId: "support",
    requester: "نیازمند تصویب",
    supplyOwner: "نیازمند تصویب",
    category: "Workspace & Equipment",
    progress: 0,
    status: "requested",
    impact: "فضای حداقل ۴۵نفره، کال‌سنتر اولیه، اتاق جلسه، فضای عملیات و مالی، شبکه، اینترنت پشتیبان، تلفن، تجهیزات اداری، رایانه، تجهیزات تست و کنترل دسترسی.",
    sourceKr: "Objective بالادستی",
    due: null,
    lastUpdate: "سند بالادستی v1.1.0"
  }
];

const prerequisiteRecords = [
  ...masterPrerequisiteRecords,
  {id:'pre-01',title:'فعال‌سازی شبکه دیبا',requestTeam:'رفاه‌جیب',objectiveId:'refahjib',requester:'کاریز',supplyOwner:'نیازمند تعیین',category:'Technology',progress:0,status:'blocked',impact:'توقف فعال‌سازی شرکت‌های نهایی‌شده رفاه‌جیب',sourceKr:'رسیدن به 50 شرکت فعال',due:null,lastUpdate:'Master OKR'},
  {id:'pre-02',title:'تأمین خط اعتباری رفاه‌جیب',requestTeam:'رفاه‌جیب',objectiveId:'refahjib',requester:'کاریز',supplyOwner:'فیض',category:'Funding',progress:20,status:'blocked',impact:'توقف تخصیص اعتبار و فعال‌سازی شرکت‌های آماده',sourceKr:'رسیدن به 50 شرکت فعال',due:null,lastUpdate:'گزارش هفتگی Owner',targetAmount:150,actualAmount:30,amountUnit:'میلیارد تومان'},
  {id:'pre-03',title:'راه‌اندازی سرویس TMS',requestTeam:'محصول و فناوری',objectiveId:'product',requester:'کیارش',supplyOwner:'نیازمند تعیین',category:'Technology',progress:10,status:'in-progress',impact:'تأخیر در Go-Live رفاه‌جیب و بیزجیب و تکمیل فرایندهای End-to-End',sourceKr:'Go-Live رفاه‌جیب و بیزجیب',due:null,lastUpdate:'Master OKR'},
  {id:'pre-04',title:'تأمین اعتبار بانک ملی یا دی',requestTeam:'محصول و فناوری',objectiveId:'product',requester:'کیارش',supplyOwner:'فیض',category:'Funding',progress:0,status:'blocked',impact:'توقف Go-Live و تخصیص اعتبار محصولات',sourceKr:'Go-Live رفاه‌جیب و بیزجیب',due:null,lastUpdate:'Master OKR'},
  {id:'pre-05',title:'Go-Live فرایندهای شرکت، تخصیص اعتبار و بازپرداخت',requestTeam:'عملیات',objectiveId:'operations',requester:'ساسان',supplyOwner:'محصول و فناوری',category:'Operations',progress:10,status:'in-progress',impact:'عدم امکان راه‌اندازی عملیات پایدار برای کاربران و شرکت‌ها',sourceKr:'سه KR فرایند عملیاتی',due:null,lastUpdate:'Master OKR'},
  {id:'pre-06',title:'استقرار CRM عملیاتی و کال‌سنتر',requestTeam:'عملیات',objectiveId:'operations',requester:'ساسان',supplyOwner:'نیازمند تعیین',category:'Technology',progress:0,status:'requested',impact:'کاهش کنترل درخواست‌ها، Escalation و کیفیت پاسخ‌گویی',sourceKr:'راه‌اندازی کال‌سنتر و فرآیند Escalation',due:null,lastUpdate:'Master OKR'},
  {id:'pre-07',title:'جذب نفر چهارم کال‌سنتر',requestTeam:'عملیات',objectiveId:'operations',requester:'ساسان',supplyOwner:'یاسین',category:'HR',progress:0,status:'requested',impact:'محدودیت ظرفیت پاسخ‌گویی کال‌سنتر اولیه',sourceKr:'راه‌اندازی کال‌سنتر اولیه',due:null,lastUpdate:'Master OKR'},
  {id:'pre-08',title:'تعیین SLA و Owner نهایی فرآیند Escalation',requestTeam:'عملیات',objectiveId:'operations',requester:'ساسان',supplyOwner:'نیازمند تصمیم مدیریت',category:'Management Decision',progress:0,status:'requested',impact:'نامشخص‌ماندن مسئولیت و زمان پاسخ بین تیم‌های داخلی',sourceKr:'تعریف فرآیند Escalation مشکلات',due:null,lastUpdate:'Master OKR'},
  {id:'pre-09',title:'تأمین فضای کاری و سخت‌افزار کال‌سنتر',requestTeam:'عملیات',objectiveId:'operations',requester:'ساسان',supplyOwner:'نیازمند تعیین',category:'Operations',progress:0,status:'requested',impact:'تأخیر در بهره‌برداری کامل کال‌سنتر اولیه',sourceKr:'راه‌اندازی کال‌سنتر اولیه',due:null,lastUpdate:'Master OKR'},
  {id:'pre-10',title:'تصویب زمان‌بندی، مالکیت، مخاطب و فرمت گزارش عملیاتی',requestTeam:'عملیات',objectiveId:'operations',requester:'ساسان',supplyOwner:'نیازمند تصمیم مدیریت',category:'Management Decision',progress:60,status:'in-progress',impact:'تداوم گزارش‌دهی غیررسمی و غیرقابل اتکا برای مدیریت',sourceKr:'گزارش عملیاتی دوره‌ای',due:null,lastUpdate:'Master OKR'}
];

const riskRecords = [
  {id:'risk-01',type:'risk',title:'نامشخص‌بودن Targetهای جیب‌پلاس',team:'جیب‌پلاس',objectiveId:'jibplus',owner:'فیض',severity:'critical',status:'open',impact:'چهار KR قابل محاسبه نیستند و سنجش پیشرفت این لاین ممکن نیست.',nextAction:'تصویب Targetهای تجاری و عملیاتی فصل',due:null,source:'Master OKR'},
  {id:'risk-02',type:'risk',title:'وابستگی اجرای امنیت به قرارداد تیم خارجی',team:'محصول و فناوری',objectiveId:'security',owner:'افشار',severity:'high',status:'open',impact:'مالک اجرایی چهار KR امنیت هنوز به قرارداد نهایی‌نشده وابسته است.',nextAction:'تعیین Owner داخلی موقت و نهایی‌کردن قرارداد',due:null,source:'Master OKR'},
  {id:'risk-03',type:'risk',title:'مغایرت Target تسهیلات بیزجیب',team:'بیزجیب',objectiveId:'bizjib',owner:'عبدی',severity:'medium',status:'open',impact:'عنوان KR عدد ۲۷۰ و ستون Target عدد ۳۷۰ را نشان می‌دهد و گزارش پیشرفت می‌تواند نادرست باشد.',nextAction:'تأیید عدد مرجع توسط Owner و اصلاح Master Data',due:null,source:'Master OKR'},
  {id:'risk-04',type:'risk',title:'ظرفیت خط اعتباری هنوز صفر است',team:'تأمین منابع',objectiveId:'funding',owner:'فیض',severity:'critical',status:'open',impact:'رشد رفاه‌جیب و بیزجیب و Go-Live محصولات به تأمین اعتبار وابسته است.',nextAction:'تعیین مسیر بانکی، مصوبه و زمان‌بندی ظرفیت قابل استفاده',due:null,source:'Master OKR'},
  {id:'risk-05',type:'risk',title:'نبود Owner و موعد قطعی برای پیش‌نیازها',team:'عملیات',objectiveId:'operations',owner:'ساسان',severity:'high',status:'open',impact:'پیش‌نیازهای بین‌تیمی بدون پاسخ‌گو و موعد قابل پیگیری و Escalation نیستند.',nextAction:'تعیین Owner تأمین و Due Date در جلسه مدیریتی',due:null,source:'تحلیل Master OKR'}
];

const decisionRecords = [
  {id:'dec-01',title:'تصویب Targetهای تجاری و عملیاتی جیب‌پلاس',team:'جیب‌پلاس',objectiveId:'jibplus',requester:'فیض',decisionMaker:'نیازمند تعیین',priority:'critical',status:'waiting',context:'چهار KR جیب‌پلاس فاقد Target هستند و پیشرفت Objective قابل محاسبه نیست.',recommendation:'Target کاربران فعال، حجم عملیات، درآمد و آمادگی End-to-End پیش از Update بعدی تصویب شود.',due:null,related:'risk-01'},
  {id:'dec-02',title:'تأیید عدد مرجع تسهیلات بیزجیب؛ ۲۷۰ یا ۳۷۰ میلیارد تومان',team:'بیزجیب',objectiveId:'bizjib',requester:'عبدی',decisionMaker:'عبدی',priority:'high',status:'waiting',context:'عنوان KR عدد ۲۷۰ و ستون Target عدد ۳۷۰ را نشان می‌دهد.',recommendation:'عدد نهایی با مبنای مصوبه اعتباری تطبیق و سپس Master Data اصلاح شود.',due:null,related:'risk-03'},
  {id:'dec-03',title:'انتخاب مسیر تأمین اعتبار از بانک ملی یا دی',team:'تأمین منابع',objectiveId:'funding',requester:'فیض',decisionMaker:'نیازمند تعیین',priority:'critical',status:'waiting',context:'نبود اعتبار بانکی، Go-Live رفاه‌جیب و بیزجیب و تخصیص تسهیلات را متوقف کرده است.',recommendation:'یک بانک به‌عنوان مسیر اصلی و بانک دوم به‌عنوان مسیر پشتیبان تعیین شود.',due:null,related:'risk-04'},
  {id:'dec-04',title:'تعیین Owner تأمین شبکه دیبا و سرویس TMS',team:'محصول و فناوری',objectiveId:'product',requester:'کیارش',decisionMaker:'نیازمند تعیین',priority:'critical',status:'waiting',context:'چند KR محصول به شبکه دیبا و TMS وابسته‌اند، اما Owner تأمین در فایل مشخص نشده است.',recommendation:'یک Owner داخلی پاسخ‌گو با موعد تحویل و مسیر Escalation تعیین شود.',due:null,related:'blocker-product-0'},
  {id:'dec-05',title:'تصویب قرارداد تیم امنیت و Owner داخلی موقت',team:'محصول و فناوری',objectiveId:'security',requester:'افشار',decisionMaker:'نیازمند تعیین',priority:'high',status:'waiting',context:'Owner اجرایی چهار KR امنیت، تیم خارجی با قرارداد در حال امضا ثبت شده است.',recommendation:'تا زمان عقد قرارداد، یک Owner داخلی مسئول ارزیابی، MFA، آسیب‌پذیری‌ها و لاگ امنیتی باشد.',due:null,related:'risk-02'},
  {id:'dec-06',title:'تصویب SLA و Owner نهایی فرآیند Escalation',team:'عملیات',objectiveId:'operations',requester:'ساسان',decisionMaker:'نیازمند تعیین',priority:'high',status:'waiting',context:'مسئولیت و زمان پاسخ بین تیم‌های داخلی برای Escalation تثبیت نشده است.',recommendation:'SLA سطح‌بندی‌شده و Owner هر سطح در جلسه اجرایی تصویب شود.',due:null,related:'pre-08'},
  {id:'dec-07',title:'تصویب قالب و چرخه گزارش عملیاتی دوره‌ای',team:'عملیات',objectiveId:'operations',requester:'ساسان',decisionMaker:'نیازمند تعیین',priority:'medium',status:'waiting',context:'زمان‌بندی، مالکیت، مخاطب و فرمت نهایی گزارش‌های عملیاتی رسمی نشده است.',recommendation:'گزارش هفتگی برای مدیریت و Snapshot دوهفته‌ای برای جلسه Board تثبیت شود.',due:null,related:'pre-10'},
  {id:'dec-08',title:'تأیید منابع لازم برای راه‌اندازی کال‌سنتر اولیه',team:'عملیات',objectiveId:'operations',requester:'ساسان',decisionMaker:'نیازمند تعیین',priority:'high',status:'waiting',context:'جذب نفر چهارم، فضای کاری، سخت‌افزار و CRM برای تکمیل کال‌سنتر لازم است.',recommendation:'بسته منابع کال‌سنتر به‌صورت یکجا تصویب و Owner هر قلم تعیین شود.',due:null,related:'pre-06'}
];

const commitmentRecords = [
  {id:'com-01',title:'Targetهای تجاری و عملیاتی جیب‌پلاس را برای چهار KR نهایی و ثبت کند',owner:'فیض',team:'جیب‌پلاس',objectiveId:'jibplus',status:'open',due:null,evidence:'Target مصوب و ثبت‌شده در Master OKR',note:'پیش‌نیاز محاسبه Progress جیب‌پلاس',source:'Decision dec-01'},
  {id:'com-02',title:'عدد مرجع تسهیلات بیزجیب؛ ۲۷۰ یا ۳۷۰ میلیارد تومان را تأیید کند',owner:'عبدی',team:'بیزجیب',objectiveId:'bizjib',status:'open',due:null,evidence:'تأیید کتبی عدد و اصلاح Master Data',note:'رفع مغایرت عنوان KR و ستون Target',source:'Decision dec-02'},
  {id:'com-03',title:'مسیر اصلی و پشتیبان تأمین اعتبار از بانک ملی یا دی را مشخص کند',owner:'فیض',team:'تأمین منابع',objectiveId:'funding',status:'open',due:null,evidence:'مصوبه مسیر بانکی و زمان‌بندی ظرفیت',note:'برای رفع توقف Go-Live لاین‌ها',source:'Decision dec-03'},
  {id:'com-04',title:'Owner تأمین شبکه دیبا و سرویس TMS را تعیین و پیگیری تحویل را آغاز کند',owner:'کیارش',team:'محصول و فناوری',objectiveId:'product',status:'in-progress',due:null,evidence:'نام Owner، موعد تحویل و مسیر Escalation',note:'وابستگی مستقیم چند KR محصول',source:'Decision dec-04'},
  {id:'com-05',title:'قرارداد تیم امنیت را نهایی و Owner داخلی موقت را معرفی کند',owner:'افشار',team:'محصول و فناوری',objectiveId:'security',status:'open',due:null,evidence:'قرارداد نهایی و ابلاغ Owner داخلی',note:'پوشش ارزیابی، MFA، آسیب‌پذیری و لاگ امنیتی',source:'Decision dec-05'},
  {id:'com-06',title:'SLA و Owner نهایی فرآیند Escalation را برای تصویب آماده کند',owner:'ساسان',team:'عملیات',objectiveId:'operations',status:'open',due:null,evidence:'سند SLA سطح‌بندی‌شده و ماتریس Ownerها',note:'تثبیت زمان پاسخ بین تیم‌های داخلی',source:'Decision dec-06'},
  {id:'com-07',title:'جذب نفر چهارم کال‌سنتر را تا مرحله شروع همکاری پیش ببرد',owner:'یاسین',team:'منابع انسانی',objectiveId:'hr',status:'open',due:null,evidence:'قرارداد یا ثبت شروع همکاری نیروی جدید',note:'افزایش ظرفیت پاسخ‌گویی کال‌سنتر',source:'Prerequisite pre-07'},
  {id:'com-08',title:'قالب و چرخه گزارش عملیاتی هفتگی و Snapshot دوهفته‌ای را تثبیت کند',owner:'ساسان',team:'عملیات',objectiveId:'operations',status:'in-progress',due:null,evidence:'قالب تأییدشده و اولین گزارش دوره‌ای',note:'مبنای گزارش‌دهی مدیریت و Board',source:'Decision dec-07'}
];
